// import { getSession } from '../utils/auth';
// import { SessionProvider } from 'next-auth/react';
import './global.css';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-gray-200">{children}</div>
      </body>
    </html>
  );
}
