// import { getSession } from '../utils/auth';
// import { SessionProvider } from 'next-auth/react';
import { Session } from 'inspector';
import { auth } from '../utils/auth';
import './global.css';
import { SessionProvider } from 'next-auth/react';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <div className="min-h-screen bg-gray-200">{children}</div>
        </SessionProvider>
      </body>
    </html>
  );
}
