export default function Index() {
  return (
    <div className="flex flex-col items-center justify-center flex-1 w-full h-screen">
      <h1 className="text-6xl">Welcome to web!</h1>
      <p className="mt-4 text-xl">Generated by create-nx-workspace</p>
    </div>
  );
}
